name: 'Code Owner Self Merge'
description: 'Lets the CODEOWNERS file determine who can merge a PR'
author: 'Orta Therox'

branding:
  icon: git-merge
  color: purple

runs:
  using: 'node12'
  main: 'index.js'
